Name:           meta-desktop-kde
Version:        1
Release:        1
License:        GPL-3.0
Summary:        Applications for the desktop from the KDE ecosystem.
Url:            https://clearlinux.org/
Group:          base
Requires:       Linux-PAM
Requires:       ModemManager
Requires:       NetworkManager
Requires:       NetworkManager-l2tp
Requires:       NetworkManager-openconnect
Requires:       NetworkManager-openvpn
Requires:       NetworkManager-vpnc
Requires:       accountsservice
Requires:       adwaita-icon-theme
Requires:       alsa-firmware
Requires:       alsa-plugins
Requires:       alsa-utils
Requires:       attica
Requires:       attica-lib
Requires:       baloo
Requires:       baloo-lib
Requires:       baloo-widgets
Requires:       baloo-widgets-lib
Requires:       bash-completion
Requires:       bluedevil
Requires:       bluez
Requires:       bluez-extras
Requires:       breeze
Requires:       breeze-gtk
Requires:       breeze-icons
Requires:       cairo-lib
Requires:       cantarell-fonts
Requires:       clear-font
Requires:       cups
Requires:       cups-filters
Requires:       cups-pk-helper
Requires:       curl
Requires:       dbus
Requires:       dbus-extras
Requires:       desktop-file-utils
Requires:       dolphin-plugins
Requires:       drkonqi
Requires:       evtest
Requires:       exiv2
Requires:       exiv2-lib
Requires:       findutils
Requires:       fontconfig
Requires:       fontconfig-data
Requires:       fontconfig-lib
Requires:       freetype
Requires:       freetype-lib
Requires:       fuse
Requires:       gcc-libs-math
Requires:       gdk-pixbuf
Requires:       glib-bin
Requires:       glib-data
Requires:       glib-lib
Requires:       glibc-lib-avx2
Requires:       gpgme
Requires:       gpgme-lib
Requires:       gsettings-desktop-schemas
Requires:       gtk+-data
Requires:       gtk+-lib
Requires:       gtk3-lib
Requires:       gutenprint
Requires:       harfbuzz
Requires:       harfbuzz-lib
Requires:       icu4c
Requires:       icu4c-lib
Requires:       kactivities
Requires:       kactivitymanagerd
Requires:       karchive
Requires:       kauth
Requires:       kauth-lib
Requires:       kbookmarks
Requires:       kcalendarcore
Requires:       kcalendarcore-lib
Requires:       kcmutils
Requires:       kcmutils-lib
Requires:       kcodecs
Requires:       kcompletion
Requires:       kconfig
Requires:       kconfigwidgets
Requires:       kcoreaddons
Requires:       kcrash
Requires:       kdbusaddons
Requires:       kdbusaddons-lib
Requires:       kde-cli-tools
Requires:       kde-gtk-config
Requires:       kdeclarative
Requires:       kdeclarative-lib
Requires:       kdecoration
Requires:       kded
Requires:       kdeplasma-addons
Requires:       kdoctools
Requires:       kdoctools-lib
Requires:       kfilemetadata
Requires:       kgamma5
Requires:       kglobalaccel
Requires:       kglobalaccel-lib
Requires:       kguiaddons
Requires:       kguiaddons-lib
Requires:       khotkeys
Requires:       ki18n
Requires:       kiconthemes
Requires:       kinfocenter
Requires:       kinit
Requires:       kio
Requires:       kio-extras
Requires:       kirigami2-lib
Requires:       kitemmodels
Requires:       kitemviews
Requires:       kjobwidgets
Requires:       kjs
Requires:       kmenuedit
Requires:       knewstuff
Requires:       knotifications
Requires:       knotifyconfig
Requires:       kpackage
Requires:       kpackage-lib
Requires:       kparts
Requires:       kplotting
Requires:       kpty
Requires:       kquickcharts-lib
Requires:       kscreen
Requires:       kscreenlocker
Requires:       kservice
Requires:       ksshaskpass
Requires:       ktextwidgets
Requires:       ktp-desktop-applets
Requires:       kwallet
Requires:       kwallet-pam
Requires:       kwayland-integration
Requires:       kwidgetsaddons
Requires:       kwin
Requires:       kwindowsystem
Requires:       kwrited
Requires:       kxmlgui
Requires:       libX11-data
Requires:       libX11-lib
Requires:       libXScrnSaver-lib
Requires:       libXau-lib
Requires:       libXcursor-lib
Requires:       libXdamage-lib
Requires:       libXdmcp-lib
Requires:       libXext-lib
Requires:       libXft-lib
Requires:       libXi-lib
Requires:       libXrender-lib
Requires:       libXtst-lib
Requires:       libXxf86vm-lib
Requires:       libassuan
Requires:       libassuan-lib
Requires:       libdrm-lib
Requires:       liberation-fonts
Requires:       libinput-data
Requires:       libinput-lib
Requires:       libinput-libexec
Requires:       libjpeg-turbo-lib
Requires:       libkscreen
Requires:       libksysguard
Requires:       libmtp
Requires:       libpng-lib
Requires:       libreswan
Requires:       librsvg-lib
Requires:       libstdc++
Requires:       libwebp-lib
Requires:       libxcb-lib
Requires:       libxslt
Requires:       libxslt-lib
Requires:       linux-firmware-wifi
Requires:       llvm-lib
Requires:       mesa
Requires:       mesa-demos
Requires:       mesa-lib
Requires:       milou
Requires:       mkfontdir
Requires:       mkfontscale
Requires:       mlocate
Requires:       network-manager-applet
Requires:       noto-cjk
Requires:       noto-emoji
Requires:       noto-fonts
Requires:       numlockx
Requires:       openldap
Requires:       openssl-lib
Requires:       oxygen
Requires:       p11-kit
Requires:       pango-lib
Requires:       perl
Requires:       perl-Config-General
Requires:       perl-Config-Tiny
Requires:       perl-Crypt-SSLeay
Requires:       perl-DBI
Requires:       perl-DateTime-TimeZone
Requires:       perl-Encode-Locale
Requires:       perl-Error
Requires:       perl-File-Listing
Requires:       perl-HTML-Parser
Requires:       perl-HTML-Tagset
Requires:       perl-HTTP-Cookies
Requires:       perl-HTTP-Date
Requires:       perl-HTTP-Message
Requires:       perl-HTTP-Negotiate
Requires:       perl-IO-HTML
Requires:       perl-LWP-MediaTypes
Requires:       perl-LWP-Protocol-https
Requires:       perl-Params-Validate
Requires:       perl-Test-Simple
Requires:       perl-Try-Tiny
Requires:       perl-URI
Requires:       perl-XML-NamespaceSupport
Requires:       perl-XML-Parser
Requires:       perl-libwww-perl
Requires:       perl-man
Requires:       phonon
Requires:       phonon-lib
Requires:       phonon-vlc
Requires:       pixman-lib
Requires:       plasma-browser-integration
Requires:       plasma-desktop
Requires:       plasma-discover
Requires:       plasma-integration
Requires:       plasma-nm
Requires:       plasma-pa
Requires:       plasma-vault
Requires:       plasma-workspace
Requires:       plasma-workspace-wallpapers
Requires:       polkit
Requires:       polkit-kde-agent
Requires:       powerdevil
Requires:       powerline-fonts
Requires:       print-manager
Requires:       pulseaudio
Requires:       pypi-cffi
Requires:       pypi-pip
Requires:       pypi-pycodestyle
Requires:       pypi-setuptools
Requires:       pypi-virtualenv
Requires:       python3-core
Requires:       python3-dev
Requires:       qqc2-desktop-style
Requires:       qt3d
Requires:       qtbase
Requires:       qtbase-extras
Requires:       qtcanvas3d
Requires:       qtcharts
Requires:       qtconnectivity
Requires:       qtdatavis3d
Requires:       qtdeclarative
Requires:       qtgamepad
Requires:       qtgraphicaleffects
Requires:       qtimageformats
Requires:       qtlocation
Requires:       qtmultimedia
Requires:       qtnetworkauth
Requires:       qtquickcontrols
Requires:       qtquickcontrols2
Requires:       qtscript
Requires:       qtscript-extras
Requires:       qtscxml
Requires:       qtsensors
Requires:       qtserialbus
Requires:       qtserialport
Requires:       qtspeech
Requires:       qtsvg
Requires:       qttools
Requires:       qttranslations
Requires:       qtvirtualkeyboard
Requires:       qtwayland
Requires:       qtwebchannel
Requires:       qtwebengine
Requires:       qtwebsockets
Requires:       qtx11extras
Requires:       qtxmlpatterns
Requires:       roboto
Requires:       samba-lib
Requires:       sddm
Requires:       sddm-autostart
Requires:       sddm-kcm
Requires:       setxkbmap
Requires:       shared-mime-info
Requires:       solid
Requires:       sonnet
Requires:       source-code-pro
Requires:       swupd-search
Requires:       systemd-extras
Requires:       systemd-lib
Requires:       systemsettings
Requires:       tdb-lib
Requires:       terminus-font
Requires:       threadweaver
Requires:       tiff-lib
Requires:       tzdata
Requires:       udisks2
Requires:       upower
Requires:       usb-modeswitch
Requires:       usb-modeswitch-data
Requires:       user-manager
Requires:       wayland
Requires:       weston
Requires:       wmctrl
Requires:       wpa_supplicant
Requires:       xauth
Requires:       xclip
Requires:       xdg-desktop-portal
Requires:       xdg-desktop-portal-gtk
Requires:       xdg-desktop-portal-kde
Requires:       xdg-user-dirs
Requires:       xdg-user-dirs-gtk
Requires:       xdg-utils
Requires:       xdotool
Requires:       xdpyinfo
Requires:       xf86-input-libinput
Requires:       xf86-video-amdgpu
Requires:       xf86-video-ati
Requires:       xf86-video-fbdev
Requires:       xf86-video-nouveau
Requires:       xf86-video-qxl
Requires:       xf86-video-vboxvideo
Requires:       xf86-video-vesa
Requires:       xf86-video-vmware
Requires:       xfontsel
Requires:       xhost
Requires:       xinit
Requires:       xinput
Requires:       xkbcomp
Requires:       xkeyboard-config
Requires:       xkill
Requires:       xl2tpd
Requires:       xmodmap
Requires:       xorg-fonts
Requires:       xorg-server
Requires:       xprop
Requires:       xrandr
Requires:       xrdb
Requires:       xrdp
Requires:       xrestop
Requires:       xsel
Requires:       xset
Requires:       xsetroot
Requires:       xterm
Requires:       xvfb-run
Requires:       xwd
Requires:       xwininfo

Suggests:       ghostscript
Suggests:       kdiff3
Suggests:       konsole
Suggests:       ksysguard
Suggests:       phin


%description
Applications for the desktop from the KDE ecosystem.

%prep

%build

%install

%files
